### ISSUE TITLE
How to link stm8.lib?

### ISSUE THREAD

**Issue by jxltom** [XaviDCR92/stm8-dce-example#2]
Following error is raised when linking with ```stm8-ld```. It looks like ```stm8.lib``` is not linked. I tried with ```-L``` and ```-l``` options, but ```stm-ld``` reports can not find library.

```
main.c:201: undefined reference to `___uint2fs'
main.c:206: undefined reference to `___fslt'
main.c:206: undefined reference to `___fslt'
main.c:217: undefined reference to `_(float, short, short, bool __restrict)'
main.c:217: undefined reference to `_(float, short, double, int, void)'
main.c:217: undefined reference to `___fsmul'
main.c:217: undefined reference to `___fs2uint'
main.c:221: undefined reference to `_(float, short, short, bool __restrict)'
main.c:221: undefined reference to `_(float, short, double, int, void)'
main.c:221: undefined reference to `___fsmul'
main.c:221: undefined reference to `___fs2uint'
```

**Comment by XaviDCR92** [comment]
This issue arises when you do arithmetic operations such as divisions or multiplications, as they rely on functions provided by the compiler. [SDCC includes both platform-specific and portable implementations](https://github.com/XaviDCR92/sdcc-gas/tree/master/device/lib) so `sdld` includes them on the link phase.
As a quick workaround, you can compile any needed source files corresponding to the portable implementations e.g.: `_fsmul.c` using the same compilation flags as `stm8-dce-example` and add them into the objects list for `stm8-ld`. While the platform-specific implementations are surely more optimized, they are written in assembly using `sdas` syntax instead of `stm8-as`, so you will need some (minor) modifications to make them work on `stm8-as`.
Therefore, should the `sdcc-gas` repository be ever merged into upstream, two versions of the assembly code should be then provided: one for `sdas` and one for `stm8-as`.

**Comment by jxltom** [comment]
Hey @XaviDCR92 many thanks for the clarification!

I've compiled and linked ```_fs2uinit.c```, ```_fs2ulong.c```, ```_fslt.c```, ```_fsmul.c```, ```_uint2fs.c```, ```_ulong2fs.c``` and ```__mulsint2slong.s``` (with a little bit modification) to remove most of the errors.

However, following errors still exist. Do you mind telling me which files should I add? Thanks!

```
.pio/build/default/src/main.o: In function `_ADC_REG':
main:(.text._ADC_REG+0xa0): undefined reference to `_(float, short, short, bool __restrict)'
main:(.text._ADC_REG+0xb0): undefined reference to `_(float, short, double, int, void)'
main:(.text._ADC_REG+0xe6): undefined reference to `_(float, short, short, bool __restrict)'
main:(.text._ADC_REG+0xf6): undefined reference to `_(float, short, double, int, void)
```

**Comment by XaviDCR92** [comment]
I am not sure what your `ADC_REG` function is doing to require such symbols. Moreover, I see their names have a parameter list in them for some reason, but can't tell you why, I'm sorry.
Could you please paste either `ADC_REG` or the problematic lines so we can find the root cause of the issue? Thanks a lot.

**Comment by jxltom** [comment]
Thanks for help!

Below the the related code, but I didn't find any thing special.

```
void ADC_REG()
{  
  float ADC_REG_max=1023;
  float ADC_REG_min=0;
  float current_value=0;
  float range=0;
  float middle=0;
  float threshold=0;

  /* Init ADC1 peripheral */
  ADC1_Init(ADC1_CONVERSIONMODE_SINGLE, ADC1_CHANNEL_6, ADC1_PRESSEL_FCPU_D10,
            ADC1_EXTTRIG_TIM, DISABLE, ADC1_ALIGN_RIGHT, ADC1_SCHMITTTRIG_CHANNEL6, DISABLE);   //单次转换、通道6、10分频、右对齐 
  
  /*Start Conversion */
  ADC1_StartConversion();  
  
  while(!ADC1_GetFlagStatus(ADC1_FLAG_EOC));//等待转换完成
  ADC1_ClearFlag(ADC1_FLAG_EOC);//软件清除   
  
  ADC_REG_value=ADC1_GetConversionValue();
  current_value=ADC_REG_value-ADC_REG_min;
  range=ADC_REG_max-ADC_REG_min;
  middle=range/2;
  threshold=range*0.05;
    
    if(current_value>(middle-threshold) && current_value<(middle+threshold))
    {
      MOTOR_STOP();                                     //停止
      STOP_State=off;   
    }
    else if(STOP_State==on)
      MOTOR_STOP();
    else 
    {
      if (current_value <= (middle-threshold))
     {
        MOTOR_FWD((middle - current_value)/middle*999);    //正转
       }
     else if (current_value >= (middle+threshold))
     {
        MOTOR_REV((current_value-middle)/middle*999);    //反转
       }
    } 
}


void MOTOR_STOP()
{      
   GPIO_Init(GPIOC, GPIO_PIN_5, GPIO_MODE_OUT_PP_LOW_FAST);    //PWM4
   
   GPIO_Init(GPIOC, GPIO_PIN_3, GPIO_MODE_OUT_PP_LOW_FAST);   //PWM2
   
   GPIO_Init(GPIOC, GPIO_PIN_4, GPIO_MODE_OUT_PP_LOW_FAST);    //PWM3
     
   GPIO_Init(GPIOA, GPIO_PIN_3, GPIO_MODE_OUT_PP_LOW_FAST);    //PWM1 
   
   Delay(1000);
      
}

void MOTOR_FWD(uint16_t PWM1)
{     
  GPIO_Init(GPIOC, GPIO_PIN_3, GPIO_MODE_OUT_PP_LOW_FAST);   //PWM2
  
  GPIO_Init(GPIOC, GPIO_PIN_5, GPIO_MODE_OUT_PP_HIGH_FAST);    //PWM4
  
  GPIO_Init(GPIOC, GPIO_PIN_4, GPIO_MODE_OUT_PP_LOW_FAST);    //PWM3
    
  /*TIM2_Pulse = CCR3_Val*/     
  TIM2_OC3Init(TIM2_OCMODE_PWM1, TIM2_OUTPUTSTATE_ENABLE, PWM1, TIM2_OCPOLARITY_HIGH);     //PWM1
}

void MOTOR_REV(uint16_t PWM3)
{  
  GPIO_Init(GPIOC, GPIO_PIN_3, GPIO_MODE_OUT_PP_HIGH_FAST);   //PWM2
    
  GPIO_Init(GPIOC, GPIO_PIN_5, GPIO_MODE_OUT_PP_LOW_FAST);    //PWM4    
    
  GPIO_Init(GPIOA, GPIO_PIN_3, GPIO_MODE_OUT_PP_LOW_FAST);    //PWM1  
  
  /*TIM1_Pulse = CCR4_Val*/
  TIM1_OC4Init(TIM1_OCMODE_PWM1, TIM1_OUTPUTSTATE_ENABLE, PWM3, TIM1_OCPOLARITY_HIGH, TIM1_OCIDLESTATE_SET);       //PWM3
}
```

**Comment by XaviDCR92** [comment]
The error message is, for some reason, very unfortunate. Please add the following files to the build:
```
_fsadd.c
_fsdiv.c
_fsmul.c
_fssub.c
```
Adding them worked for me.

**Comment by jxltom** [comment]
Thanks! It finally working!

It will be nice, If there is a precompiled stm8.lib version provided for sdcc-gas :smile:

**Comment by XaviDCR92** [comment]
If I'm not mistaken, the `stm8-binutils-gdb` should be modified to include `stm8.lib`, similarly to how `libc.a` is included. I should take a look at how to do that.

**Comment by jxltom** [comment]
That will be great! It will be much easier for the linking.

**Comment by jxltom** [comment]
Thanks for the help! I will close this issue since it is actually solved.

I created another issue https://github.com/XaviDCR92/stm8-binutils-gdb/issues/1 to tracking the precompiled stm8.lib feature.
